//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bauer.Developer.Test.RestaurantGuide.DataAccess
{
    using Bauer.Developer.Test.RestaurantGuide.Domain;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BauerDeveloperTestEntities : DbContext
    {
        public BauerDeveloperTestEntities()
            : base("name=BauerDeveloperTestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RestaurantCuisine> RestaurantCuisines { get; set; }
        public virtual DbSet<Cuisine> Cuisines { get; set; }
    }
}
